// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoCardapio.Models;

#nullable disable

namespace ProjetoCardapio.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoCardapio.Models.Dias", b =>
                {
                    b.Property<int>("DiasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiasId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiasId"));

                    b.Property<string>("NomeDia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaNome");

                    b.HasKey("DiasId");

                    b.ToTable("Dias");
                });

            modelBuilder.Entity("ProjetoCardapio.Models.Periodo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PeriodoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("NomePeriodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PeriodoNome");

                    b.HasKey("id");

                    b.ToTable("Periodo");
                });

            modelBuilder.Entity("ProjetoCardapio.Models.Pratos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PratoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasId")
                        .HasColumnType("int");

                    b.Property<string>("LinkImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LinkImagem");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("int");

                    b.Property<string>("PratoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PratoNome");

                    b.HasKey("Id");

                    b.HasIndex("DiasId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("Pratos");
                });

            modelBuilder.Entity("ProjetoCardapio.Models.Presencas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PresencaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuantidadeAlunos")
                        .HasColumnType("int")
                        .HasColumnName("QuantidadeAlunos");

                    b.Property<int>("SalasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalasId");

                    b.ToTable("Presencas");
                });

            modelBuilder.Entity("ProjetoCardapio.Models.Salas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SalasId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("NomeSalas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SalasNome");

                    b.HasKey("id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("ProjetoCardapio.Models.Pratos", b =>
                {
                    b.HasOne("ProjetoCardapio.Models.Dias", "Dias")
                        .WithMany()
                        .HasForeignKey("DiasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoCardapio.Models.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dias");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("ProjetoCardapio.Models.Presencas", b =>
                {
                    b.HasOne("ProjetoCardapio.Models.Salas", "Salas")
                        .WithMany()
                        .HasForeignKey("SalasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salas");
                });
#pragma warning restore 612, 618
        }
    }
}
